[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.24'

fs_permissions = [
    { access = "read", path = "./out"},
    { access = "read-write", path = "./deployments"},
]

gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_nova = "${ARBITRUM_NOVA_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
zora = "${ZORA_RPC_URL}"
zora_sepolia = "${ZORA_SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
avalanche_fuji = "${AVALANCHE_FUJI_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"
fantom_testnet = "${FANTOM_TESTNET_RPC_URL}"
moonbeam = "${MOONBEAM_RPC_URL}"
moonbeam_testnet = "${MOONBEAM_TESTNET_RPC_URL}"
rari = "${RARI_RPC_URL}"
rari_testnet = "${RARI_TESTNET_RPC_URL}"
mantle = "${MANTLE_RPC_URL}"
mantle_sepolia = "${MANTLE_SEPOLIA_RPC_URL}"
mode = "${MODE_RPC_URL}"
mode_sepolia = "${MODE_SEPOLIA_RPC_URL}"
zksync = "${ZKSYNC_RPC_URL}"
zksync_sepolia = "${ZKSYNC_SEPOLIA_RPC_URL}"
bnb = "${BNB_RPC_URL}"
bnb_testnet = "${BNB_TESTNET_RPC_URL}"
opbnb = "${OPBNB_RPC_URL}"
opbnb_testnet = "${OPBNB_TESTNET_RPC_URL}"
degen = "${DEGEN_RPC_URL}"
cyber = "${CYBER_RPC_URL}"
blast = "${BLAST_RPC_URL}"
scroll = "${SCROLL_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"
ape = "${APE_RPC_URL}"
ape_curtis = "${APE_CURTIS_RPC_URL}"
zero = "${ZERO_RPC_URL}"
lisk = "${LISK_RPC_URL}"
sanko = "${SANKO_RPC_URL}"
superposition = "${SUPERPOSITION_RPC_URL}"
courage_asleep_southern = "${COURAGE_ASLEEP_SOUTHERN_RPC_URL}"
breeze_contain_secret = "${BREEZE_CONTAIN_SECRET_RPC_URL}"
ink = "${INK_RPC_URL}"
appchain = "${APPCHAIN_RPC_URL}"
plume = "${PLUME_RPC_URL}"
abstract_chain = "${ABSTRACT_CHAIN_RPC_URL}"
berachain = "${BERACHAIN_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"
soneium = "${SONEIUM_RPC_URL}"
glue = "${GLUE_RPC_URL}"
story = "${STORY_RPC_URL}"
lumia = "${LUMIA_RPC_URL}"
